### ISSUE TITLE
Any information on how to get this setup in HA and/or in general.

### ISSUE THREAD

**Issue by tmorris0221** [tedpearson/electric-usage-downloader#14]
I was able to follow the instructions on how to setup the config.yaml file but not sure where to go after that. I have setup an Influxdb on my HA. Any assistance with next steps? I see all the contents under internal/app but unsure what to do with those.

**Comment by tedpearson** [comment]
Hi @tmorris0221, the easiest way to run this would be to download one of the binaries that matches your system from the [releases page](https://github.com/tedpearson/electric-usage-downloader/releases), make it executable (`chmod +x filename`) and run it via `./filename`.

Hope this helps, let me know if you have more questions.

**Comment by tedpearson** [comment]
So it's able to log you in, but when it tries to query the data from the api, instead of getting a json response it's getting an HTML webpage. I don't know if your co-op is doing something special in their SmartHub deployment, or if this is a new change that's rolling out. Debugging this would probably involve figuring out exactly what the webpage that's loading is trying to do, making sure you're able to log in normally and download the data using the website, and whatever else that leads to.

Let me know if you want to continue down one of these paths. I could probably modify the debug output to display the whole HTML output and we can see what it's getting. Or I could figure out an equivalent script to do the same thing. Also you could try verifying that you can download your data from SmartHub manually.

**Comment by tmorris0221** [comment]
Thanks for all your help! I just checked and do not see an option to export my usage explorer data from my smarthub account. Maybe if you could add more detail debug data, that would help determine which direction may be best. I'm going to reach out to my provider to see if the export option can be enabled.

**Comment by tedpearson** [comment]
On my Co-op's SmartHub site, you go to either "Usage Explorer", scroll down to "Green Button Download My Data" or to "Usage Management" then "Download Your Data" tab. Just mentioning that in case you were looking in the wrong place.

I just released [v2.3.1](https://github.com/tedpearson/electric-usage-downloader/releases/tag/v2.3.1) which should now log the entire response from the api poll endpoint, if you want to see the entire page the server is returning.

**Comment by tmorris0221** [comment]
I checked and don't seem to have that button available or a Usage Management tab. Here are the results from the latest debug after successful authorization.

Fetching data from SmartHub API...

DEBUG: Response from poll endpoint:
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <title>Startup...</title>
    <script type="text/javascript">
        function addParamAndReload(key, value) {
            key = encodeURIComponent(key); 
            value = encodeURIComponent(value);
            var kvp = document.location.search.substr(1).split('&');
            if (kvp == "") {
                document.location.search = key + "=" + value;
            } else {
                var i = kvp.length; var x; while (i--) {
                    x = kvp[i].split('=');
                    if (x[0] == key) {
                        x[1] = value;
                        kvp[i] = x.join('=');
                        break;
                    }
                }
                if (i < 0) { 
                    kvp[kvp.length] = [key, value].join('='); 
                }
                //this will reload the page, it's likely better to store this until finished
                document.location.search = kvp.join('&');
            }
        }
        function setFragmentCookie() {
            var currentHash = self.document.location.hash.substring(1);
            if (currentHash == undefined || currentHash == null || currentHash == "") {
                currentHash = '#';
            }
            addParamAndReload('urlFragment', currentHash);            
        }
    </script>
</head>
<body onload="setFragmentCookie();">
</body>
</html>
panic: All attempts fail:
        #1: invalid character '<' looking for beginning of value

goroutine 1 [running]:
main.main()
        /home/runner/work/electric-usage-downloader/electric-usage-downloader/main.go:9 +0x38

**Comment by tedpearson** [comment]
I don't see anything very interesting in that output. Seems like as you said, they just don't support downloading or if they do it's not at that url.

**Comment by tmorris0221** [comment]
I've been chatting with my provider and it doesn't appear they support exporting the data to any thing other than a print chart, which is lame. Thanks for your responses and the help thus far. If they ever update their site, maybe I'll revisit this.

**Comment by tedpearson** [comment]
Booooo. Sorry to hear that. I'll close this issue for now then, best of luck.
